In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv("../data/Telco_Dataset.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../data/Telco_Dataset.csv'

In [3]:
df = pd.read_csv("../data/Telco_Dataset.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../data/Telco_Dataset.csv'

In [4]:
df = pd.read_csv("../data/Telco_Dataset.csv", encoding='latin1')

FileNotFoundError: [Errno 2] No such file or directory: '../data/Telco_Dataset.csv'

In [5]:
import os

print(os.getcwd())

C:\Users\Nihal Reddy

In [6]:
os.listdir()

['.anaconda',
 '.aws',
 '.azure',
 '.bash_history',
 '.cagent',
 '.conda',
 '.condarc',
 '.config',
 '.continuum',
 '.copilot',
 '.docker',
 '.eclipse',
 '.ghcp-appmod',
 '.ghcp-appmod-java',
 '.git',
 '.gitconfig',
 '.gk',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.kube',
 '.lemminx',
 '.lesshst',
 '.m2',
 '.matplotlib',
 '.node_repl_history',
 '.p2',
 '.packettracer',
 '.streamlit',
 '.viminfo',
 '.VirtualBox',
 '.vscode',
 '.vscode-shared',
 'anaconda3',
 'AppData',
 'Application Data',
 'battery-report.html',
 'Business-Sales-Analytics',
 'Churn-Analytics',
 'Churn_Analysis.ipynb',
 'Cisco Packet Tracer 9.0.0',
 'Contacts',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'eclipse',
 'eclipse-workspace',
 'Favorites',
 'FEDF-GIT-A4',
 'FEDF1',
 'fedf2',
 'fedfgit',
 'file.txt',
 'Links',
 'Local Settings',
 'Matrix Operations & Eigen Values.ipynb',
 'Microsoft',
 'Music',
 'My Documents',
 'NetHood',
 'Nihal',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{b2122fe4-fa12-11ef-8b4d-c8a3e8cd65a8}.TM.blf',
 'NTUSER.DAT{b2122fe4-fa12-11ef-8b4d-c8a3e8cd65a8}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{b2122fe4-fa12-11ef-8b4d-c8a3e8cd65a8}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'PycharmProjects',
 'Recent',
 'Saved Games',
 'scikit_learn_data',
 'sci_env',
 'Searches',
 'SendTo',
 'Start Menu',
 'student-app',
 'Templates',
 'Untitled Folder',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Untitled4.ipynb',
 'Untitled5.ipynb',
 'Untitled6.ipynb',
 'Untitled7.ipynb',
 'Untitled8.ipynb',
 'Videos',
 'VirtualBox VMs',
 'webpage-git']

In [7]:
os.listdir("data")

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'data'

In [8]:
import os
print(os.getcwd())

C:\Users\Nihal Reddy

In [9]:
os.listdir()

['.anaconda',
 '.aws',
 '.azure',
 '.bash_history',
 '.cagent',
 '.conda',
 '.condarc',
 '.config',
 '.continuum',
 '.copilot',
 '.docker',
 '.eclipse',
 '.ghcp-appmod',
 '.ghcp-appmod-java',
 '.git',
 '.gitconfig',
 '.gk',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.kube',
 '.lemminx',
 '.lesshst',
 '.m2',
 '.matplotlib',
 '.node_repl_history',
 '.p2',
 '.packettracer',
 '.streamlit',
 '.viminfo',
 '.VirtualBox',
 '.vscode',
 '.vscode-shared',
 'anaconda3',
 'AppData',
 'Application Data',
 'battery-report.html',
 'Business-Sales-Analytics',
 'Churn-Analytics',
 'Churn_Analysis.ipynb',
 'Cisco Packet Tracer 9.0.0',
 'Contacts',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'eclipse',
 'eclipse-workspace',
 'Favorites',
 'FEDF-GIT-A4',
 'FEDF1',
 'fedf2',
 'fedfgit',
 'file.txt',
 'Links',
 'Local Settings',
 'Matrix Operations & Eigen Values.ipynb',
 'Microsoft',
 'Music',
 'My Documents',
 'NetHood',
 'Nihal',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{b2122fe4-fa12-11ef-8b4d-c8a3e8cd65a8}.TM.blf',
 'NTUSER.DAT{b2122fe4-fa12-11ef-8b4d-c8a3e8cd65a8}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{b2122fe4-fa12-11ef-8b4d-c8a3e8cd65a8}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'PycharmProjects',
 'Recent',
 'Saved Games',
 'scikit_learn_data',
 'sci_env',
 'Searches',
 'SendTo',
 'Start Menu',
 'student-app',
 'Templates',
 'Untitled Folder',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Untitled4.ipynb',
 'Untitled5.ipynb',
 'Untitled6.ipynb',
 'Untitled7.ipynb',
 'Untitled8.ipynb',
 'Videos',
 'VirtualBox VMs',
 'webpage-git']

In [10]:
os.listdir("..")

['All Users',
 'Default',
 'Default User',
 'desktop.ini',
 'Nihal Reddy',
 'Public']

In [11]:
df = pd.read_csv("Churn-Analytics/data/Telco_Dataset.csv")

In [12]:
import os

os.listdir("Churn-Analytics")

['.ipynb_checkpoints',
 'cleaned_data',
 'dashboard',
 'data',
 'notebook',
 'report',
 'screenshots']

In [13]:
os.listdir("Churn-Analytics/data")

['Telco_Dataset.csv']

In [14]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [15]:
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [16]:
df.shape

(7043, 21)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [18]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df['Churn'].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [21]:
round(df['Churn'].value_counts(normalize=True)*100,2)

Churn
No     73.46
Yes    26.54
Name: proportion, dtype: float64

In [22]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [23]:
df['TotalCharges'].head(10)

0      29.85
1     1889.5
2     108.15
3    1840.75
4     151.65
5      820.5
6     1949.4
7      301.9
8    3046.05
9    3487.95
Name: TotalCharges, dtype: object

In [24]:
df['TotalCharges'].dtype

dtype('O')

In [25]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [26]:
df['TotalCharges'].isnull().sum()

np.int64(11)

In [27]:
df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)

C:\Users\Nihal Reddy\AppData\Local\Temp\ipykernel_13644\2840544469.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)

In [28]:
df['TotalCharges'].isnull().sum()

np.int64(0)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [30]:
# Tenure Group
df['Tenure_Group'] = pd.cut(
    df['tenure'],
    bins=[0,12,24,48,72],
    labels=[
        '0-12 Months',
        '13-24 Months',
        '25-48 Months',
        '49-72 Months'
    ]
)

# Monthly Charge Group
df['MonthlyCharge_Group'] = pd.cut(
    df['MonthlyCharges'],
    bins=[0,35,70,120],
    labels=['Low','Medium','High']
)

# Churn Flag
df['Churn_Flag'] = df['Churn'].map({
    'No':0,
    'Yes':1
})

In [31]:
df.groupby('Contract')['Churn_Flag'].mean()*100

Contract
Month-to-month    42.709677
One year          11.269518
Two year           2.831858
Name: Churn_Flag, dtype: float64

In [32]:
df.groupby('InternetService')['Churn_Flag'].mean()*100

InternetService
DSL            18.959108
Fiber optic    41.892765
No              7.404980
Name: Churn_Flag, dtype: float64

In [33]:
df.groupby('PaymentMethod')['Churn_Flag'].mean()*100

PaymentMethod
Bank transfer (automatic)    16.709845
Credit card (automatic)      15.243101
Electronic check             45.285412
Mailed check                 19.106700
Name: Churn_Flag, dtype: float64

In [34]:
df.groupby('Tenure_Group', observed=True)['Churn_Flag'].mean()*100

Tenure_Group
0-12 Months     47.678161
13-24 Months    28.710938
25-48 Months    20.388959
49-72 Months     9.513176
Name: Churn_Flag, dtype: float64

In [35]:
df.groupby('SeniorCitizen')['Churn_Flag'].mean()*100

SeniorCitizen
0    23.606168
1    41.681261
Name: Churn_Flag, dtype: float64

In [36]:
df.groupby('gender')['Churn_Flag'].mean()*100

gender
Female    26.920872
Male      26.160338
Name: Churn_Flag, dtype: float64

In [37]:
df.groupby('Partner')['Churn_Flag'].mean()*100

Partner
No     32.957979
Yes    19.664903
Name: Churn_Flag, dtype: float64

In [38]:
df.groupby('Dependents')['Churn_Flag'].mean()*100

Dependents
No     31.279140
Yes    15.450237
Name: Churn_Flag, dtype: float64

In [39]:
df.groupby('Churn')['MonthlyCharges'].mean()

Churn
No     61.265124
Yes    74.441332
Name: MonthlyCharges, dtype: float64

In [40]:
df.groupby('Churn')['tenure'].mean()

Churn
No     37.569965
Yes    17.979133
Name: tenure, dtype: float64

In [41]:
df.groupby('Churn')['TotalCharges'].mean()

Churn
No     2552.882494
Yes    1531.796094
Name: TotalCharges, dtype: float64

In [42]:
df.to_csv(
    "Churn-Analytics/cleaned_data/telco_churn_cleaned.csv",
    index=False
)

In [43]:
df.to_csv(
    "Churn-Analytics/cleaned_data/telco_churn_cleaned.csv",
    index=False
)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customerID           7043 non-null   object
 1   gender               7043 non-null   object
 2   SeniorCitizen        7043 non-null   int64
 3   Partner              7043 non-null   object
 4   Dependents           7043 non-null   object
 5   tenure               7043 non-null   int64
 6   PhoneService         7043 non-null   object
 7   MultipleLines        7043 non-null   object
 8   InternetService      7043 non-null   object
 9   OnlineSecurity       7043 non-null   object
 10  OnlineBackup         7043 non-null   object
 11  DeviceProtection     7043 non-null   object
 12  TechSupport          7043 non-null   object
 13  StreamingTV          7043 non-null   object
 14  StreamingMovies      7043 non-null   object
 15  Contract             7043 non-null   object
 16  PaperlessBilling     7043 non-null   object
 17  PaymentMethod        7043 non-null   object
 18  MonthlyCharges       7043 non-null   float64
 19  TotalCharges         7043 non-null   float64
 20  Churn                7043 non-null   object
 21  Tenure_Group         7032 non-null   category
 22  MonthlyCharge_Group  7043 non-null   category
 23  Churn_Flag           7043 non-null   int64
dtypes: category(2), float64(2), int64(3), object(17)
memory usage: 1.2+ MB

In [45]:
df['Tenure_Group'] = pd.cut(
    df['tenure'],
    bins=[-1,12,24,48,72],
    labels=[
        '0-12 Months',
        '13-24 Months',
        '25-48 Months',
        '49-72 Months'
    ]
)

In [46]:
df['Tenure_Group'].isnull().sum()

np.int64(0)

In [47]:
df.to_csv(
    "Churn-Analytics/cleaned_data/telco_churn_cleaned.csv",
    index=False
)